from __future__ import print_function
import numpy as np
from loadTxt import *
import matplotlib.pyplot as plt
from mpl_toolkits.basemap import Basemap as Basemap
from matplotlib.colors import rgb2hex
from matplotlib.patches import Polygon


countFreq, posFreq, negFreq, neuFreq = write_to_csv('./rawData.csv')
# Lambert Conformal map of lower 48 states.
m = Basemap(llcrnrlon=-119,llcrnrlat=22,urcrnrlon=-64,urcrnrlat=49,
            projection='lcc',lat_1=33,lat_2=45,lon_0=-95)
# draw state boundaries.
# data from U.S Census Bureau
# http://www.census.gov/geo/www/cob/st2000.html
shp_info = m.readshapefile('st99_d00','states',drawbounds=True)
# population density by state from
# http://en.wikipedia.org/wiki/List_of_U.S._states_by_population_density
pos = {
'New Jersey':  posFreq['NJ'] + 0.0,
'Rhode Island':   posFreq['RI'] + 0.0,
'Massachusetts':   posFreq['MA'] + 0.0,
'Connecticut':    posFreq['CT'] + 0.0,
'Maryland':   posFreq['MD'] + 0.0,
'New York':    posFreq['NY'] + 0.0,
'Delaware':    posFreq['DE'] + 0.0,
'Florida':     posFreq['FL'] + 0.0,
'Ohio':  posFreq['OH'] + 0.0,
'Pennsylvania':  posFreq['PA'] + 0.0,
'Illinois':    posFreq['IL'] + 0.0,
'California':  posFreq['CA'] + 0.0,
'Hawaii':  posFreq['HI'] + 0.0,
'Virginia':    posFreq['VA'] + 0.0,
'Michigan':    posFreq['MI'] + 0.0,
'Indiana':    posFreq['IN'] + 0.0,
'North Carolina':  posFreq['NC'] + 0.0,
'Georgia':     posFreq['GA'] + 0.0,
'Tennessee':   posFreq['TN'] + 0.0,
'New Hampshire':   posFreq['NH'] + 0.0,
'South Carolina':  posFreq['SC'] + 0.0,
'Louisiana':   posFreq['LA'] + 0.0,
'Kentucky':   posFreq['KY'] + 0.0,
'Wisconsin':  posFreq['WI'] + 0.0,
'Washington':  posFreq['WA'] + 0.0,
'Alabama':     posFreq['AL'] + 0.0,
'Missouri':    posFreq['MO'] + 0.0,
'Texas':   posFreq['TX'] + 0.0,
'West Virginia':   posFreq['WV'] + 0.0,
'Vermont':     posFreq['VT'] + 0.0,
'Minnesota':  posFreq['MN'] + 0.0,
'Mississippi':   posFreq['MS'] + 0.0,
'Iowa':  posFreq['IA'] + 0.0,
'Arkansas':    posFreq['AR'] + 0.0,
'Oklahoma':    posFreq['OK'] + 0.0,
'Arizona':     posFreq['AZ'] + 0.0,
'Colorado':    posFreq['CO'] + 0.0,
'Maine':  posFreq['ME'] + 0.0,
'Oregon':  posFreq['OR'] + 0.0,
'Kansas':  posFreq['KS'] + 0.0,
'Utah':  posFreq['UT'] + 0.0,
'Nebraska':    posFreq['NE'] + 0.0,
'Nevada':  posFreq['NV'] + 0.0,
'Idaho':   posFreq['ID'] + 0.0,
'New Mexico':  posFreq['NM'] + 0.0,
'South Dakota':  posFreq['SD'] + 0.0,
'North Dakota':  posFreq['ND'] + 0.0,
'Montana':     posFreq['MT'] + 0.0,
'Wyoming':      posFreq['WY'] + 0.0,
'Alaska':     posFreq['AK'] + 0.0}


neg = {
'New Jersey':  negFreq['NJ'] + 0.0,
'Rhode Island':   negFreq['RI'] + 0.0,
'Massachusetts':   negFreq['MA'] + 0.0,
'Connecticut':    negFreq['CT'] + 0.0,
'Maryland':   negFreq['MD'] + 0.0,
'New York':    negFreq['NY'] + 0.0,
'Delaware':    negFreq['DE'] + 0.0,
'Florida':     negFreq['FL'] + 0.0,
'Ohio':  negFreq['OH'] + 0.0,
'Pennsylvania':  negFreq['PA'] + 0.0,
'Illinois':    negFreq['IL'] + 0.0,
'California':  negFreq['CA'] + 0.0,
'Hawaii':  negFreq['HI'] + 0.0,
'Virginia':    negFreq['VA'] + 0.0,
'Michigan':    negFreq['MI'] + 0.0,
'Indiana':    negFreq['IN'] + 0.0,
'North Carolina':  negFreq['NC'] + 0.0,
'Georgia':     negFreq['GA'] + 0.0,
'Tennessee':   negFreq['TN'] + 0.0,
'New Hampshire':   negFreq['NH'] + 0.0,
'South Carolina':  negFreq['SC'] + 0.0,
'Louisiana':   negFreq['LA'] + 0.0,
'Kentucky':   negFreq['KY'] + 0.0,
'Wisconsin':  negFreq['WI'] + 0.0,
'Washington':  negFreq['WA'] + 0.0,
'Alabama':     negFreq['AL'] + 0.0,
'Missouri':    negFreq['MO'] + 0.0,
'Texas':   negFreq['TX'] + 0.0,
'West Virginia':   negFreq['WV'] + 0.0,
'Vermont':     negFreq['VT'] + 0.0,
'Minnesota':  negFreq['MN'] + 0.0,
'Mississippi':   negFreq['MS'] + 0.0,
'Iowa':  negFreq['IA'] + 0.0,
'Arkansas':    negFreq['AR'] + 0.0,
'Oklahoma':    negFreq['OK'] + 0.0,
'Arizona':     negFreq['AZ'] + 0.0,
'Colorado':    negFreq['CO'] + 0.0,
'Maine':  negFreq['ME'] + 0.0,
'Oregon':  negFreq['OR'] + 0.0,
'Kansas':  negFreq['KS'] + 0.0,
'Utah':  negFreq['UT'] + 0.0,
'Nebraska':    negFreq['NE'] + 0.0,
'Nevada':  negFreq['NV'] + 0.0,
'Idaho':   negFreq['ID'] + 0.0,
'New Mexico':  negFreq['NM'] + 0.0,
'South Dakota':  negFreq['SD'] + 0.0,
'North Dakota':  negFreq['ND'] + 0.0,
'Montana':     negFreq['MT'] + 0.0,
'Wyoming':      negFreq['WY'] + 0.0,
'Alaska':     negFreq['AK'] + 0.0}

neu = {
'New Jersey':  neuFreq['NJ'] + 0.0,
'Rhode Island':   neuFreq['RI'] + 0.0,
'Massachusetts':   neuFreq['MA'] + 0.0,
'Connecticut':    neuFreq['CT'] + 0.0,
'Maryland':   neuFreq['MD'] + 0.0,
'New York':    neuFreq['NY'] + 0.0,
'Delaware':    neuFreq['DE'] + 0.0,
'Florida':     neuFreq['FL'] + 0.0,
'Ohio':  neuFreq['OH'] + 0.0,
'Pennsylvania':  neuFreq['PA'] + 0.0,
'Illinois':    neuFreq['IL'] + 0.0,
'California':  neuFreq['CA'] + 0.0,
'Hawaii':  neuFreq['HI'] + 0.0,
'Virginia':    neuFreq['VA'] + 0.0,
'Michigan':    neuFreq['MI'] + 0.0,
'Indiana':    neuFreq['IN'] + 0.0,
'North Carolina':  neuFreq['NC'] + 0.0,
'Georgia':     neuFreq['GA'] + 0.0,
'Tennessee':   neuFreq['TN'] + 0.0,
'New Hampshire':   neuFreq['NH'] + 0.0,
'South Carolina':  neuFreq['SC'] + 0.0,
'Louisiana':   neuFreq['LA'] + 0.0,
'Kentucky':   neuFreq['KY'] + 0.0,
'Wisconsin':  neuFreq['WI'] + 0.0,
'Washington':  neuFreq['WA'] + 0.0,
'Alabama':     neuFreq['AL'] + 0.0,
'Missouri':    neuFreq['MO'] + 0.0,
'Texas':   neuFreq['TX'] + 0.0,
'West Virginia':   neuFreq['WV'] + 0.0,
'Vermont':     neuFreq['VT'] + 0.0,
'Minnesota':  neuFreq['MN'] + 0.0,
'Mississippi':   neuFreq['MS'] + 0.0,
'Iowa':  neuFreq['IA'] + 0.0,
'Arkansas':    neuFreq['AR'] + 0.0,
'Oklahoma':    neuFreq['OK'] + 0.0,
'Arizona':     neuFreq['AZ'] + 0.0,
'Colorado':    neuFreq['CO'] + 0.0,
'Maine':  neuFreq['ME'] + 0.0,
'Oregon':  neuFreq['OR'] + 0.0,
'Kansas':  neuFreq['KS'] + 0.0,
'Utah':  neuFreq['UT'] + 0.0,
'Nebraska':    neuFreq['NE'] + 0.0,
'Nevada':  neuFreq['NV'] + 0.0,
'Idaho':   neuFreq['ID'] + 0.0,
'New Mexico':  neuFreq['NM'] + 0.0,
'South Dakota':  neuFreq['SD'] + 0.0,
'North Dakota':  neuFreq['ND'] + 0.0,
'Montana':     neuFreq['MT'] + 0.0,
'Wyoming':      neuFreq['WY'] + 0.0,
'Alaska':     neuFreq['AK'] + 0.0}

amount = {
'New Jersey':  countFreq['NJ'] + 0.0,
'Rhode Island':   countFreq['RI'] + 0.0,
'Massachusetts':   countFreq['MA'] + 0.0,
'Connecticut':    countFreq['CT'] + 0.0,
'Maryland':   countFreq['MD'] + 0.0,
'New York':    countFreq['NY'] + 0.0,
'Delaware':    countFreq['DE'] + 0.0,
'Florida':     countFreq['FL'] + 0.0,
'Ohio':  countFreq['OH'] + 0.0,
'Pennsylvania':  countFreq['PA'] + 0.0,
'Illinois':    countFreq['IL'] + 0.0,
'California':  countFreq['CA'] + 0.0,
'Hawaii':  countFreq['HI'] + 0.0,
'Virginia':    countFreq['VA'] + 0.0,
'Michigan':    countFreq['MI'] + 0.0,
'Indiana':    countFreq['IN'] + 0.0,
'North Carolina':  countFreq['NC'] + 0.0,
'Georgia':     countFreq['GA'] + 0.0,
'Tennessee':   countFreq['TN'] + 0.0,
'New Hampshire':   countFreq['NH'] + 0.0,
'South Carolina':  countFreq['SC'] + 0.0,
'Louisiana':   countFreq['LA'] + 0.0,
'Kentucky':   countFreq['KY'] + 0.0,
'Wisconsin':  countFreq['WI'] + 0.0,
'Washington':  countFreq['WA'] + 0.0,
'Alabama':     countFreq['AL'] + 0.0,
'Missouri':    countFreq['MO'] + 0.0,
'Texas':   countFreq['TX'] + 0.0,
'West Virginia':   countFreq['WV'] + 0.0,
'Vermont':     countFreq['VT'] + 0.0,
'Minnesota':  countFreq['MN'] + 0.0,
'Mississippi':   countFreq['MS'] + 0.0,
'Iowa':  countFreq['IA'] + 0.0,
'Arkansas':    countFreq['AR'] + 0.0,
'Oklahoma':    countFreq['OK'] + 0.0,
'Arizona':     countFreq['AZ'] + 0.0,
'Colorado':    countFreq['CO'] + 0.0,
'Maine':  countFreq['ME'] + 0.0,
'Oregon':  countFreq['OR'] + 0.0,
'Kansas':  countFreq['KS'] + 0.0,
'Utah':  countFreq['UT'] + 0.0,
'Nebraska':    countFreq['NE'] + 0.0,
'Nevada':  countFreq['NV'] + 0.0,
'Idaho':   countFreq['ID'] + 0.0,
'New Mexico':  countFreq['NM'] + 0.0,
'South Dakota':  countFreq['SD'] + 0.0,
'North Dakota':  countFreq['ND'] + 0.0,
'Montana':     countFreq['MT'] + 0.0,
'Wyoming':      countFreq['WY'] + 0.0,
'Alaska':     countFreq['AK'] + 0.0}


popdensity = {
'New Jersey':  438.00,
'Rhode Island':   387.35,
'Massachusetts':   312.68,
'Connecticut':	  271.40,
'Maryland':   209.23,
'New York':    155.18,
'Delaware':    154.87,
'Florida':     114.43,
'Ohio':	 107.05,
'Pennsylvania':	 105.80,
'Illinois':    86.27,
'California':  83.85,
'Hawaii':  72.83,
'Virginia':    69.03,
'Michigan':    67.55,
'Indiana':    65.46,
'North Carolina':  63.80,
'Georgia':     54.59,
'Tennessee':   53.29,
'New Hampshire':   53.20,
'South Carolina':  51.45,
'Louisiana':   39.61,
'Kentucky':   39.28,
'Wisconsin':  38.13,
'Washington':  34.20,
'Alabama':     33.84,
'Missouri':    31.36,
'Texas':   30.75,
'West Virginia':   29.00,
'Vermont':     25.41,
'Minnesota':  23.86,
'Mississippi':	 23.42,
'Iowa':	 20.22,
'Arkansas':    19.82,
'Oklahoma':    19.40,
'Arizona':     17.43,
'Colorado':    16.01,
'Maine':  15.95,
'Oregon':  13.76,
'Kansas':  12.69,
'Utah':	 10.50,
'Nebraska':    8.60,
'Nevada':  7.03,
'Idaho':   6.04,
'New Mexico':  5.79,
'South Dakota':	 3.84,
'North Dakota':	 3.59,
'Montana':     2.39,
'Wyoming':      1.96,
'Alaska':     0.42}

rate = {
'New Jersey':  amount['New Jersey'] / popdensity['New Jersey'],
'Rhode Island':   amount['Rhode Island'] / popdensity['Rhode Island'],
'Massachusetts':   amount['Massachusetts'] / popdensity['Massachusetts'],
'Connecticut':    amount['Connecticut'] / popdensity['Connecticut'],
'Maryland':   amount['Maryland'] / popdensity['Maryland'],
'New York':    amount['New York'] / popdensity['New York'],
'Delaware':    amount['Delaware'] / popdensity['Delaware'],
'Florida':     amount['Florida'] / popdensity['Florida'],
'Ohio':  amount['Ohio'] / popdensity['Ohio'],
'Pennsylvania':  amount['Pennsylvania'] / popdensity['Pennsylvania'],
'Illinois':    amount['Illinois'] / popdensity['Illinois'],
'California':  amount['California'] / popdensity['California'],
'Hawaii':  amount['Hawaii'] / popdensity['Hawaii'],
'Virginia':    amount['Virginia'] / popdensity['Virginia'],
'Michigan':    amount['Michigan'] / popdensity['Michigan'],
'Indiana':    amount['Indiana'] / popdensity['Indiana'],
'North Carolina':  amount['North Carolina'] / popdensity['North Carolina'],
'Georgia':     amount['Georgia'] / popdensity['Georgia'],
'Tennessee':   amount['Tennessee'] / popdensity['Tennessee'],
'New Hampshire':   amount['New Hampshire'] / popdensity['New Hampshire'],
'South Carolina':  amount['South Carolina'] / popdensity['South Carolina'],
'Louisiana':   amount['Louisiana'] / popdensity['Louisiana'],
'Kentucky':   amount['Kentucky'] / popdensity['Kentucky'],
'Wisconsin':  amount['Wisconsin'] / popdensity['Wisconsin'],
'Washington':  amount['Washington'] / popdensity['Washington'],
'Alabama':     amount['Alabama'] / popdensity['Alabama'],
'Missouri':    amount['Missouri'] / popdensity['Missouri'],
'Texas':   amount['Texas'] / popdensity['Texas'],
'West Virginia':   amount['West Virginia'] / popdensity['West Virginia'],
'Vermont':     amount['Vermont'] / popdensity['Vermont'],
'Minnesota':  amount['Minnesota'] / popdensity['Minnesota'],
'Mississippi':   amount['Mississippi'] / popdensity['Mississippi'],
'Iowa':  amount['Iowa'] / popdensity['Iowa'],
'Arkansas':    amount['Arkansas'] / popdensity['Arkansas'],
'Oklahoma':    amount['Oklahoma'] / popdensity['Oklahoma'],
'Arizona':     amount['Arizona'] / popdensity['Arizona'],
'Colorado':    amount['Colorado'] / popdensity['Colorado'],
'Maine':  amount['Maine'] / popdensity['Maine'],
'Oregon':  amount['Oregon'] / popdensity['Oregon'],
'Kansas':  amount['Kansas'] / popdensity['Kansas'],
'Utah':  amount['Utah'] / popdensity['Utah'],
'Nebraska':    amount['Nebraska'] / popdensity['Nebraska'],
'Nevada':  amount['Nevada'] / popdensity['Nevada'],
'Idaho':   amount['Idaho'] / popdensity['Idaho'],
'New Mexico':  amount['New Mexico'] / popdensity['New Mexico'],
'South Dakota':  amount['South Dakota'] / popdensity['South Dakota'],
'North Dakota':  amount['North Dakota'] / popdensity['North Dakota'],
'Montana':     amount['Montana'] / popdensity['Montana'],
'Wyoming':      amount['Wyoming'] / popdensity['Wyoming'],
'Alaska':     amount['Alaska'] / popdensity['Alaska']}

ratePos = {
'New Jersey':  pos['New Jersey'] / popdensity['New Jersey'],
'Rhode Island':   pos['Rhode Island'] / popdensity['Rhode Island'],
'Massachusetts':   pos['Massachusetts'] / popdensity['Massachusetts'],
'Connecticut':    pos['Connecticut'] / popdensity['Connecticut'],
'Maryland':   pos['Maryland'] / popdensity['Maryland'],
'New York':    pos['New York'] / popdensity['New York'],
'Delaware':    pos['Delaware'] / popdensity['Delaware'],
'Florida':     pos['Florida'] / popdensity['Florida'],
'Ohio':  pos['Ohio'] / popdensity['Ohio'],
'Pennsylvania':  pos['Pennsylvania'] / popdensity['Pennsylvania'],
'Illinois':    pos['Illinois'] / popdensity['Illinois'],
'California':  pos['California'] / popdensity['California'],
'Hawaii':  pos['Hawaii'] / popdensity['Hawaii'],
'Virginia':    pos['Virginia'] / popdensity['Virginia'],
'Michigan':    pos['Michigan'] / popdensity['Michigan'],
'Indiana':    pos['Indiana'] / popdensity['Indiana'],
'North Carolina':  pos['North Carolina'] / popdensity['North Carolina'],
'Georgia':     pos['Georgia'] / popdensity['Georgia'],
'Tennessee':   pos['Tennessee'] / popdensity['Tennessee'],
'New Hampshire':   pos['New Hampshire'] / popdensity['New Hampshire'],
'South Carolina':  pos['South Carolina'] / popdensity['South Carolina'],
'Louisiana':   pos['Louisiana'] / popdensity['Louisiana'],
'Kentucky':   pos['Kentucky'] / popdensity['Kentucky'],
'Wisconsin':  pos['Wisconsin'] / popdensity['Wisconsin'],
'Washington':  pos['Washington'] / popdensity['Washington'],
'Alabama':     pos['Alabama'] / popdensity['Alabama'],
'Missouri':    pos['Missouri'] / popdensity['Missouri'],
'Texas':   pos['Texas'] / popdensity['Texas'],
'West Virginia':   pos['West Virginia'] / popdensity['West Virginia'],
'Vermont':     pos['Vermont'] / popdensity['Vermont'],
'Minnesota':  pos['Minnesota'] / popdensity['Minnesota'],
'Mississippi':   pos['Mississippi'] / popdensity['Mississippi'],
'Iowa':  pos['Iowa'] / popdensity['Iowa'],
'Arkansas':    pos['Arkansas'] / popdensity['Arkansas'],
'Oklahoma':    pos['Oklahoma'] / popdensity['Oklahoma'],
'Arizona':     pos['Arizona'] / popdensity['Arizona'],
'Colorado':    pos['Colorado'] / popdensity['Colorado'],
'Maine':  pos['Maine'] / popdensity['Maine'],
'Oregon':  pos['Oregon'] / popdensity['Oregon'],
'Kansas':  pos['Kansas'] / popdensity['Kansas'],
'Utah':  pos['Utah'] / popdensity['Utah'],
'Nebraska':    pos['Nebraska'] / popdensity['Nebraska'],
'Nevada':  pos['Nevada'] / popdensity['Nevada'],
'Idaho':   pos['Idaho'] / popdensity['Idaho'],
'New Mexico':  pos['New Mexico'] / popdensity['New Mexico'],
'South Dakota':  pos['South Dakota'] / popdensity['South Dakota'],
'North Dakota':  pos['North Dakota'] / popdensity['North Dakota'],
'Montana':     pos['Montana'] / popdensity['Montana'],
'Wyoming':      pos['Wyoming'] / popdensity['Wyoming'],
'Alaska':     pos['Alaska'] / popdensity['Alaska']}

rateNeg = {
'New Jersey':  neg['New Jersey'] / popdensity['New Jersey'],
'Rhode Island':   neg['Rhode Island'] / popdensity['Rhode Island'],
'Massachusetts':   neg['Massachusetts'] / popdensity['Massachusetts'],
'Connecticut':    neg['Connecticut'] / popdensity['Connecticut'],
'Maryland':   neg['Maryland'] / popdensity['Maryland'],
'New York':    neg['New York'] / popdensity['New York'],
'Delaware':    neg['Delaware'] / popdensity['Delaware'],
'Florida':     neg['Florida'] / popdensity['Florida'],
'Ohio':  neg['Ohio'] / popdensity['Ohio'],
'Pennsylvania':  neg['Pennsylvania'] / popdensity['Pennsylvania'],
'Illinois':    neg['Illinois'] / popdensity['Illinois'],
'California':  neg['California'] / popdensity['California'],
'Hawaii':  neg['Hawaii'] / popdensity['Hawaii'],
'Virginia':    neg['Virginia'] / popdensity['Virginia'],
'Michigan':    neg['Michigan'] / popdensity['Michigan'],
'Indiana':    neg['Indiana'] / popdensity['Indiana'],
'North Carolina':  neg['North Carolina'] / popdensity['North Carolina'],
'Georgia':     neg['Georgia'] / popdensity['Georgia'],
'Tennessee':   neg['Tennessee'] / popdensity['Tennessee'],
'New Hampshire':   neg['New Hampshire'] / popdensity['New Hampshire'],
'South Carolina':  neg['South Carolina'] / popdensity['South Carolina'],
'Louisiana':   neg['Louisiana'] / popdensity['Louisiana'],
'Kentucky':   neg['Kentucky'] / popdensity['Kentucky'],
'Wisconsin':  neg['Wisconsin'] / popdensity['Wisconsin'],
'Washington':  neg['Washington'] / popdensity['Washington'],
'Alabama':     neg['Alabama'] / popdensity['Alabama'],
'Missouri':    neg['Missouri'] / popdensity['Missouri'],
'Texas':   neg['Texas'] / popdensity['Texas'],
'West Virginia':   neg['West Virginia'] / popdensity['West Virginia'],
'Vermont':     neg['Vermont'] / popdensity['Vermont'],
'Minnesota':  neg['Minnesota'] / popdensity['Minnesota'],
'Mississippi':   neg['Mississippi'] / popdensity['Mississippi'],
'Iowa':  neg['Iowa'] / popdensity['Iowa'],
'Arkansas':    neg['Arkansas'] / popdensity['Arkansas'],
'Oklahoma':    neg['Oklahoma'] / popdensity['Oklahoma'],
'Arizona':     neg['Arizona'] / popdensity['Arizona'],
'Colorado':    neg['Colorado'] / popdensity['Colorado'],
'Maine':  neg['Maine'] / popdensity['Maine'],
'Oregon':  neg['Oregon'] / popdensity['Oregon'],
'Kansas':  neg['Kansas'] / popdensity['Kansas'],
'Utah':  neg['Utah'] / popdensity['Utah'],
'Nebraska':    neg['Nebraska'] / popdensity['Nebraska'],
'Nevada':  neg['Nevada'] / popdensity['Nevada'],
'Idaho':   neg['Idaho'] / popdensity['Idaho'],
'New Mexico':  neg['New Mexico'] / popdensity['New Mexico'],
'South Dakota':  neg['South Dakota'] / popdensity['South Dakota'],
'North Dakota':  neg['North Dakota'] / popdensity['North Dakota'],
'Montana':     neg['Montana'] / popdensity['Montana'],
'Wyoming':      neg['Wyoming'] / popdensity['Wyoming'],
'Alaska':     neg['Alaska'] / popdensity['Alaska']}

rateNeu = {
'New Jersey':  neu['New Jersey'] / popdensity['New Jersey'],
'Rhode Island':   neu['Rhode Island'] / popdensity['Rhode Island'],
'Massachusetts':   neu['Massachusetts'] / popdensity['Massachusetts'],
'Connecticut':    neu['Connecticut'] / popdensity['Connecticut'],
'Maryland':   neu['Maryland'] / popdensity['Maryland'],
'New York':    neu['New York'] / popdensity['New York'],
'Delaware':    neu['Delaware'] / popdensity['Delaware'],
'Florida':     neu['Florida'] / popdensity['Florida'],
'Ohio':  neu['Ohio'] / popdensity['Ohio'],
'Pennsylvania':  neu['Pennsylvania'] / popdensity['Pennsylvania'],
'Illinois':    neu['Illinois'] / popdensity['Illinois'],
'California':  neu['California'] / popdensity['California'],
'Hawaii':  neu['Hawaii'] / popdensity['Hawaii'],
'Virginia':    neu['Virginia'] / popdensity['Virginia'],
'Michigan':    neu['Michigan'] / popdensity['Michigan'],
'Indiana':    neu['Indiana'] / popdensity['Indiana'],
'North Carolina':  neu['North Carolina'] / popdensity['North Carolina'],
'Georgia':     neu['Georgia'] / popdensity['Georgia'],
'Tennessee':   neu['Tennessee'] / popdensity['Tennessee'],
'New Hampshire':   neu['New Hampshire'] / popdensity['New Hampshire'],
'South Carolina':  neu['South Carolina'] / popdensity['South Carolina'],
'Louisiana':   neu['Louisiana'] / popdensity['Louisiana'],
'Kentucky':   neu['Kentucky'] / popdensity['Kentucky'],
'Wisconsin':  neu['Wisconsin'] / popdensity['Wisconsin'],
'Washington':  neu['Washington'] / popdensity['Washington'],
'Alabama':     neu['Alabama'] / popdensity['Alabama'],
'Missouri':    neu['Missouri'] / popdensity['Missouri'],
'Texas':   neu['Texas'] / popdensity['Texas'],
'West Virginia':   neu['West Virginia'] / popdensity['West Virginia'],
'Vermont':     neu['Vermont'] / popdensity['Vermont'],
'Minnesota':  neu['Minnesota'] / popdensity['Minnesota'],
'Mississippi':   neu['Mississippi'] / popdensity['Mississippi'],
'Iowa':  neu['Iowa'] / popdensity['Iowa'],
'Arkansas':    neu['Arkansas'] / popdensity['Arkansas'],
'Oklahoma':    neu['Oklahoma'] / popdensity['Oklahoma'],
'Arizona':     neu['Arizona'] / popdensity['Arizona'],
'Colorado':    neu['Colorado'] / popdensity['Colorado'],
'Maine':  neu['Maine'] / popdensity['Maine'],
'Oregon':  neu['Oregon'] / popdensity['Oregon'],
'Kansas':  neu['Kansas'] / popdensity['Kansas'],
'Utah':  neu['Utah'] / popdensity['Utah'],
'Nebraska':    neu['Nebraska'] / popdensity['Nebraska'],
'Nevada':  neu['Nevada'] / popdensity['Nevada'],
'Idaho':   neu['Idaho'] / popdensity['Idaho'],
'New Mexico':  neu['New Mexico'] / popdensity['New Mexico'],
'South Dakota':  neu['South Dakota'] / popdensity['South Dakota'],
'North Dakota':  neu['North Dakota'] / popdensity['North Dakota'],
'Montana':     neu['Montana'] / popdensity['Montana'],
'Wyoming':      neu['Wyoming'] / popdensity['Wyoming'],
'Alaska':     neu['Alaska'] / popdensity['Alaska']}

print('Realative Count: ', rate, '\n')

print(shp_info)
# choose a color for each state based on population density.
colors={}
statenames=[]
cmap = plt.cm.hot # use 'hot' colormap
vmin = 0; vmax = 450 # set range.
print(m.states_info[0].keys())
for shapedict in m.states_info:
    statename = shapedict['NAME']
    # skip DC and Puerto Rico.
    if statename not in ['District of Columbia','Puerto Rico']:
        pop = rateNeu[statename]
        # calling colormap with value between 0 and 1 returns
        # rgba value.  Invert color range (hot colors are high
        # population), take sqrt root to spread out colors more.
        colors[statename] = cmap(1.-np.sqrt((pop-vmin)/(vmax-vmin)))[:3]
    statenames.append(statename)
# cycle through state names, color each one.
ax = plt.gca() # get current axes instance
for nshape,seg in enumerate(m.states):
    # skip DC and Puerto Rico.
    if statenames[nshape] not in ['District of Columbia','Puerto Rico']:
        color = rgb2hex(colors[statenames[nshape]]) 
        poly = Polygon(seg,facecolor=color,edgecolor=color)
        ax.add_patch(poly)
# draw meridians and parallels.
m.drawparallels(np.arange(25,65,20),labels=[1,0,0,0])
m.drawmeridians(np.arange(-120,-40,20),labels=[0,0,0,1])
plt.title('Normalized Neutral Count by Tweets')
plt.show()